const dummyContribuables = [
    {
        nom: 'Doe',
        prenom: 'John',
        dateNaiss: '1990-01-15',
        sex: 'masculin',
        pays: 'France',
        adress: '123 Main Street, City',
        lieuNaiss: 'Paris',
        email: 'john.doe@example.com',
        telephone: '123-456-7890',

    },
    {
        nom: 'Smith',
        prenom: 'Jane',
        dateNaiss: '1985-05-20',
        sex: 'féminin',
        pays: 'USA',
        adress: '456 Oak Avenue, Town',
        lieuNaiss: 'New York',
        email: 'jane.smith@example.com',
        telephone: '987-654-3210',

    },
    {
        nom: 'Johnson',
        prenom: 'Bob',
        dateNaiss: '1988-08-08',
        sex: 'masculin',
        pays: 'Canada',
        adress: '789 Pine Street, Village',
        lieuNaiss: 'Toronto',
        email: 'bob.johnson@example.com',
        telephone: '555-123-4567',

    },
    {
        nom: 'Lee',
        prenom: 'Alice',
        dateNaiss: '1992-03-25',
        sex: 'féminin',
        pays: 'Australia',
        adress: '101 Willow Street, Suburb',
        lieuNaiss: 'Sydney',
        email: 'alice.lee@example.com',
        telephone: '999-888-7777',

    },
    {
        nom: 'Chen',
        prenom: 'David',
        dateNaiss: '1983-11-12',
        sex: 'masculin',
        pays: 'China',
        adress: '234 Bamboo Lane, Rural',
        lieuNaiss: 'Beijing',
        email: 'david.chen@example.com',
        telephone: '777-666-5555',

    },
    {
        nom: 'Garcia',
        prenom: 'Maria',
        dateNaiss: '1987-07-07',
        sex: 'féminin',
        pays: 'Spain',
        adress: '567 Olive Avenue, Coastal',
        lieuNaiss: 'Barcelona',
        email: 'maria.garcia@example.com',
        telephone: '444-333-2222',

    },
    {
        nom: 'Kumar',
        prenom: 'Raj',
        dateNaiss: '1995-04-30',
        sex: 'masculin',
        pays: 'India',
        adress: '890 Curry Street, Urban',
        lieuNaiss: 'Delhi',
        email: 'raj.kumar@example.com',
        telephone: '222-111-0000',

    },
    {
        nom: 'Tanaka',
        prenom: 'Yuki',
        dateNaiss: '1989-09-22',
        sex: 'féminin',
        pays: 'Japan',
        adress: '123 Sakura Lane, Mountainous',
        lieuNaiss: 'Tokyo',
        email: 'yuki.tanaka@example.com',
        telephone: '333-444-5555',

    },
    {
        nom: 'Olsen',
        prenom: 'Erik',
        dateNaiss: '1993-06-18',
        sex: 'masculin',
        pays: 'Norway',
        adress: '456 Fjord Street, Arctic',
        lieuNaiss: 'Oslo',
        email: 'erik.olsen@example.com',
        telephone: '777-888-9999',

    },
    {
        nom: 'Wang',
        prenom: 'Lily',
        dateNaiss: '1986-12-05',
        sex: 'féminin',
        pays: 'China',
        adress: '789 Jade Avenue, Rural',
        lieuNaiss: 'Shanghai',
        email: 'lily.wang@example.com',
        telephone: '999-000-1111',

    },
]